### ISSUE TITLE
组件承载不显示

### ISSUE THREAD

**Issue by Statfine** [xiaolin3303/wx-charts-demo#10]
图表是否只能在页面中使用， 用Component承载不显示，不报错

**Comment by Rickonzqh** [comment]
解决了没，我也遇到这个问题，好像直接放简单的canvas都不行

**Comment by Rickonzqh** [comment]
wxcharts.js 第1928行改成 
this.context = wx.createCanvasContext(opts.canvasId,opts.document);
然后调用的时候加参数 document:this,
 参考：https://segmentfault.com/q/1010000012854159?tdsourcetag=s_pcqq_aiomsg
